### ISSUE TITLE
pushshift server is down which causes infinite backoff

### ISSUE THREAD

**Issue by karlicoss** [seanbreckenridge/pushshift_comment_export#1]
Seems that API is down https://github.com/pushshift/api/issues/127
I think this causes [backoff](https://github.com/seanbreckenridge/pushshift_comment_export/blob/master/pushshift_comment_export/__main__.py#L14-L15) to infinitely backoff, always trying to request the first page.
I only noticed because my systemd jobs have a time limit (8 hours or something) -- not sure how are you running yours, but it's possible that they have been trying to backoff for a week now :scream: 
Perhaps worth adding `max_tries` or something like that, so it fails earlier?

**Comment by purarue** [comment]
Ah, no -- I rarely use reddit nowadays so I have this job disabled, I use rexport most of the time

pushed a version to here and pypi with `max_tries=5`

thanks for letting me know
